name: Feature Request
description: Suggest a new feature or enhancement
labels: ["type: feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      placeholder: "I'm frustrated when..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: textarea
    id: additional
    attributes:
      label: Additional context
